cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.to_cart, name='to_cart'),
    path('adjust/<item_id>/', views.adj_cart, name='adj_cart'),
    path('remove/<item_id>/', views.rem_from_cart, name='rem_from_cart'),
    path('add/<item_id>/', views.add_item_to_cart, name='add_item_to_cart'),
]

fitness_point/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('offers/', include('offers.urls')),
    path('accounts/', include('allauth.urls')),
    path('membership/', include('membership.urls')),
    path('sec_checkout/', include('sec_checkout.urls')),
    path('user_profile/', include('user_profiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

offers/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_offers, name='offers'),
    path('add_offer/', views.add_offer, name='add_offer'),
    path('<int:offer_id>/', views.offer_details, name='offer_details'),
    path('update_offer/<int:offer_id>/', views.upd_offer, name='upd_offer'),
    path('delete_offer/<int:offer_id>/', views.del_offer, name='del_offer'),
]

offers/models.py
from django.db import models


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)
    user_friendly = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_user_friendly_name(self):
        return self.user_friendly


class Offer(models.Model):
    category = models.ForeignKey(
        'Category', null=True, blank=True, on_delete=models.SET_NULL)
    descr = models.TextField()
    name = models.CharField(max_length=254)
    image = models.ImageField(null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)  
    day_one = models.CharField(max_length=254, null=True, blank=True)
    day_two = models.CharField(max_length=254, null=True, blank=True)
    day_span = models.CharField(max_length=254, null=True, blank=True)
    time_one = models.CharField(max_length=254, null=True, blank=True)
    time_two = models.CharField(max_length=254, null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    is_shoe = models.BooleanField(default=False, null=True, blank=True)
    is_course = models.BooleanField(default=True, null=True, blank=True)
    has_sizes = models.BooleanField(default=False, null=True, blank=True)
    for_beginners = models.BooleanField(default=False, null=True, blank=True)

    def __str__(self):
        return self.name

sec_checkout/models.py
import uuid
from decimal import Decimal
from django.db import models
from offers.models import Offer
from django.db.models import Sum
from django.conf import settings
from user_profiles.models import UserProfile
from django_countries.fields import CountryField


class Order(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True, related_name='orders')
    order_nr = models.CharField(max_length=32, null=False, editable=False)
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_nr = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    gr_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    original_cart = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(
        max_length=254, null=False, blank=False, default='')

    def _generate_order_nr(self):

        """ Generates a random, unique order number using UUID """

        return uuid.uuid4().hex.upper()

    def update_total(self):

        """ Updates grand total each time a line item is added,
        accounting for delivery costs. """

        self.order_total = self.lineitems.aggregate(
            Sum('lineitem_total'))['lineitem_total__sum'] or 0
        if self.order_total < settings.FREE_DEL:
            self.delivery = settings.DEL_COSTS
        else:
            self.delivery = 0
        self.gr_total = self.order_total + Decimal(self.delivery)
        self.save()

    def save(self, *args, **kwargs):

        """ Overrides the original save method to set the order number
        if it hasn't been set already. """

        if not self.order_nr:
            self.order_nr = self._generate_order_nr()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_nr


class OrderLineItem(models.Model):
    qty = models.IntegerField(null=False, blank=False, default=0)
    item_sz = models.CharField(max_length=4, null=True, blank=True)
    offer = models.ForeignKey(
        Offer, null=False, blank=False, on_delete=models.CASCADE)
    lineitem_total = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, blank=False, editable=False)
    order = models.ForeignKey(
        Order, null=False, blank=False, on_delete=models.CASCADE, related_name='lineitems')

    def save(self, *args, **kwargs):

        """ Overrides the original save method to set the lineitem total
        and update the order total. """

        self.lineitem_total = self.offer.price * self.qty
        super().save(*args, **kwargs)


    # Not sure to include it 
    # def __str__(self):
    #     return f'SKU {self.offer.sku} on order {self.order.order_nr}'

offers/forms.py
from django import forms
from .models import Offer, Category
from .widgets import CustomClearableFileInput


class OfferForm(forms.ModelForm):

    class Meta:
        model = Offer
        fields = '__all__'

    image = forms.ImageField(
        label='Image', required=False, widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        user_friendly = [
            (c.id, c.get_user_friendly_name()) for c in categories]

        self.fields['category'].choices = user_friendly
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-0 rounded-0'
            # !!!

offers/views.py
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from .models import Offer, Category
from django.db.models.functions import Lower
from .forms import OfferForm


def all_offers(request):

    """ A view to show all offers, including search queries and sorting """
    sorting = None
    search_query = None
    sorting_direction = None
    categories_to_search = None
    offers = Offer.objects.all()

    if request.GET:
        if 'q' in request.GET:
            search_query = request.GET['q']
            if not search_query:
                messages.error(request, "You need to enter a search criteria.")
                return redirect(reverse('offers'))

            queries_to_search = Q(name__icontains=search_query) \
                | Q(descr__icontains=search_query) \
                | Q(day_one__icontains=search_query) \
                | Q(day_two__icontains=search_query) \
                | Q(day_span__icontains=search_query) \
                | Q(time_one__icontains=search_query) \
                | Q(time_two__icontains=search_query)
            offers = offers.filter(queries_to_search)

        if 'sort' in request.GET:
            sort_key = request.GET['sort']
            sorting = sort_key
            if sort_key == 'name':
                sort_key = 'lower_name'
                offers = offers.annotate(lower_name=Lower('name'))
            if sort_key == 'category':
                sort_key = 'category__name'

            if 'direction' in request.GET:
                sorting_direction = request.GET['direction']
                if sorting_direction == 'desc':
                    sort_key = f'-{sort_key}'
            offers = offers.order_by(sort_key)

        if 'category' in request.GET:
            categories_to_search = request.GET['category'].split(',')
            offers = offers.filter(category__name__in=categories_to_search)
            categories_to_search = Category.objects.filter(
                name__in=categories_to_search)

    curr_sorting = f'{sorting}_{sorting_direction}'

    content = {
        'offers': offers,
        'to_search': search_query,
        'curr_sorting': curr_sorting,
        'curr_categories': categories_to_search,
    }
    return render(request, 'offers/offers.html', content)


def offer_details(request, offer_id):

    """ A view to show individual details from each offer """

    offer = get_object_or_404(Offer, pk=offer_id)

    content = {
        'offer': offer,
    }
    return render(request, 'offers/offer_details.html', content)


@login_required
def add_offer(request):

    """ Adds an offer to the store (superuser) """

    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do this.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = OfferForm(request.POST, request.FILES)
        if form.is_valid():
            offer = form.save()
            messages.success(request, 'Successfully added new offer!')
            return redirect(reverse('offer_details', args=[offer.id]))
        else:
            messages.error(
                request, 'Failed to add the offer. \
                Please ensure the form is valid.')
    else:
        form = OfferForm()

    template = 'offers/add_offer.html'
    content = {
        'form': form,
    }
    return render(request, template, content)


@login_required
def upd_offer(request, offer_id):

    """ Edits an offer in the store (superuser) """

    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do this.')
        return redirect(reverse('home'))

    offer = get_object_or_404(Offer, pk=offer_id)
    if request.method == 'POST':
        form = OfferForm(request.POST, request.FILES, instance=offer)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated the offer!')
            return redirect(reverse('offer_details', args=[offer.id]))
        else:
            messages.error(
                request, 'Failed to update the offer. \
                Please ensure the form is valid.')
    else:
        form = OfferForm(instance=offer)
        messages.info(request, f'You are updating: {offer.name}')

    template = 'offers/upd_offer.html'
    content = {
        'form': form,
        'offer': offer,
    }
    return render(request, template, content)


@login_required
def del_offer(request, offer_id):

    """ Deletes an offer from the store (superuser) """

    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do this.')
        return redirect(reverse('home'))

    offer = get_object_or_404(Offer, pk=offer_id)
    offer.delete()
    messages.success(request, 'Offer successfully deleted!')
    return redirect(reverse('offers'))

offers/templates/offers/add_offer.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-cont">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="dark-background"></div>
    <div class="container management-cont">
        <div class="row">
            <div class="col-12 col-md-6">
                <h2 class="logo-font mb-4 text-uppercase mt-lg-5">Offer Management</h2>
                <div class="white-hr w100"></div>
                <h5 class="">Add an Offer</h5>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-6 mb-5 mt-3">
                <form method="POST" action="{% url 'add_offer' %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                    <div class="text-right">
                        <a class="btn redish-border text-white rounded-0" href="{% url 'offers' %}">Cancel</a>
                        <button class="btn redish-bg px-5 text-white text-uppercase redish-hover rounded-0" type="submit">Add Offer</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
        <script type="text/javascript">
            $('#new-image').change(function() {
                var file = $('#new-image')[0].files[0];
                $('#filename').text(`Image will be set to: ${file.name}`);
            });
        </script>
{% endblock %}

offers/templates/offers/offer_details.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-cont">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="dark-background"></div>
    <div class="scroll-top-btn d-none no-pointer-events">
        <a class="btt-link d-flex h-100">
            <i class="fas fa-chevron-up mx-auto my-auto text-white"></i>
        </a>	
    </div>
    <div class="container-fluid mt-lg-5">
        <div class="row">
            <div class="white-hr d-none d-lg-block w-50"></div>
            <div class="col-12 col-md-10 col-lg-5 offset-lg-2">
                <div class="image-container my-md-5">
                    {% if offer.image %}
                    <a href="{{ offer.image.url }}" target="_blank">
                        <img class="card-img-top img-fluid" src="{{ offer.image.url }}">
                    </a>
                    {% else %}
                    <a href="#" target="_blank">
                        <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ offer.name }}">
                    </a>
                    {% endif %}
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4 delails-wrapper ml-3">
                <div class="offer-details-container mb-5 mt-md-5">
                    <p class="mb-0 lead text-uppercase"><strong>{{ offer.name }}</strong></p>
                    <p class="offers-price in-details lead mb-2 mt-2 font-weight-bold">
                        <span class="floating-dollar">$</span> {{ offer.price }}
                        <span class="floating-cents"></span>
                    </p>
                    <p class="small mt-1 mb-0">
                        {% if offer.category %}
                            <a class="text-muted" href="{% url 'offers' %}?category={{ offer.category.name }}">
                                <i class="fab fa-buffer mr-1"></i>
                                {{ offer.category.user_friendly }}
                            </a>
                        {% else %}
                            <a class="text-muted" href="#">
                                <i class="fab fa-buffer mr-1"></i>
                                Offer
                            </a>
                        {% endif %}
                    </p>
                    {% if offer.is_course %}
                    <small class="text-muted">
                        <i class="fas fa-clock mr-1"></i>
                        {{ offer.time_one }} and {{ offer.time_two }}
                    </small>
                    <p>
                        <small class="text-muted">
                            <i class="fas fa-calendar-alt mr-1"></i>
                            {{ offer.day_one|capfirst }} {{ offer.day_span }} {{ offer.day_two|capfirst }}
                        </small>
                    </p>
                    {% else %}
                    <small class="text-muted">
                        <i class="fas fa-check mr-1"></i>
                        Best quality - certified
                    </small>
                    <p>
                        <small class="text-muted">
                            <i class="fas fa-dolly mr-1"></i>
                            No shipping - pick it up here
                        </small>
                    </p>
                    {% endif %}
                    {% if request.user.is_superuser %}
                        <small class="ml-0">
                            <a href="{% url 'upd_offer' offer.id %}">Update</a> | 
                            <a class="text-danger" href="{% url 'del_offer' offer.id %}">Delete</a>
                        </small>
                    {% endif %}
                    <p class="mt-3">
                        {{ offer.descr }}
                    </p>
                    <form class="form" action="{% url 'add_item_to_cart' offer.id %}" method="POST">
                        {% csrf_token %}
                        <div class="form-row">
                            {% with sz=offer.has_sizes sh=offer.is_shoe %}
                            {% if sz and not sh %}
                                <div class="col-12">
                                    <p><strong>Size:</strong></p>
                                    <select class="form-control rounded-0 w-50" name="item_sz" id="id_item_sz">
                                        <option value="xs">XS</option>
                                        <option value="s">S</option>
                                        <option value="m" selected>M</option>
                                        <option value="l">L</option>
                                        <option value="xl">XL</option>
                                    </select>
                                </div>
                            {% elif sz and sh %}
                                <div class="col-12">
                                    <p><strong>Size:</strong></p>
                                    <select class="form-control rounded-0 w-50" name="item_sz" id="id_item_sz_shoes">
                                        <option value="6">6</option>
                                        <option value="6.5">6.5</option>
                                        <option value="7">7</option>
                                        <option value="7.5">7.5</option>
                                        <option value="8">8</option>
                                        <option value="8.5" selected>8.5</option>
                                        <option value="9">9</option>
                                        <option value="9.5">9.5</option>
                                        <option value="10">10</option>
                                        <option value="10.5">10.5</option>
                                        <option value="11">11</option>
                                        <option value="11.5">11.5</option>
                                        <option value="12">12</option>
                                        <option value="12.5">12.5</option>
                                        <option value="13">13</option>
                                        <option value="14">14</option>
                                        <option value="15">15</option>
                                    </select>
                                </div>
                            {% endif %}
                            <div class="col-12">
                                <p class="mt-3"><strong>Quantity:</strong></p>
                                <div class="form-group w-50">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <button class="decr-qty-btn btn redish-bg" data-item_id="{{ offer.id }}"
                                                id="decr-qty_{{ offer.id }}">
                                                <span class="icon no-pointer-events">
                                                    <i class="fas fa-minus no-pointer-events"></i>
                                                </span>
                                            </button>
                                        </div>
                                        <input class="form-control dark-white-bg qty-input" type="number" name="qty"
                                            value="1" min="1" max="99" data-item_id="{{ offer.id }}"
                                            id="id_qty_{{ offer.id }}">
                                        <div class="input-group-append">
                                            <button class="incr-qty-btn btn redish-bg" data-item_id="{{ offer.id }}"
                                                id="incr-qty_{{ offer.id }}">
                                                <span class="icon no-pointer-events">
                                                    <i class="fas fa-plus no-pointer-events"></i>
                                                </span>
                                            </button>
                                        </div>
                                    </div> 
                                </div>
                            </div>
                            <div class="col">
                                <a href="{% url 'offers' %}" class="btn btn-outline-black redish-border rounded-0 mt-5">
                                    <span class="icon">
                                        <i class="text-white fas fa-chevron-left"></i>
                                    </span>
                                    <span class="text-white text-uppercase">back to shop</span>
                                </a>
                                <input type="submit"
                                    class="btn text-white redish-hover redish-bg rounded-0 text-uppercase mt-5"
                                    value="Add to Cart">
                            </div>
                            <input type="hidden" name="curr_url" value="{{ request.path }}">
                            {% endwith %}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'offers/includes/qty_input_btns_script.html' %}
{% endblock %}

offers/templates/offers/upd_offer.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-cont">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="dark-background"></div>
    <div class="container management-cont">
        <div class="row">
            <div class="col-12 col-md-6">
                <h2 class="logo-font mb-4 text-uppercase mt-5 text-white">Offer Management</h2>
                <div class="white-hr w100"></div>
                <h5 class="text-white">Update an Offer</h5>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-6 mb-5 mt-3">
                <form method="POST" action="{% url 'upd_offer' offer.id %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                    <div class="text-right">
                        <a class="btn redish-border text-white rounded-0" href="{% url 'offers' %}">Cancel</a>
                        <button class="btn redish-bg redish-hover text-white text-uppercase rounded-0" type="submit">Update Offer</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}